### ISSUE TITLE
Somali language (so) request

### ISSUE THREAD

**Issue by accesstechnology-mike** [AceCentre/TranslateAndTTS#1]
Can this additional language option be included, please?

**Comment by willwade** [comment]
Yeah - not possible using the current setup. NB: it uses translate.google.com - and So doesn't have a TTS engine for that lang e.g. note no speak button https://translate.google.com/?sl=la&tl=so&text=hello%20world&op=translate 

But Intend to provide a different wrapper that will do this - BUT you will likely need your own Google Cloud Key for this (it's going to use https://github.com/mediatechlab/tts-wrapper)

**Comment by willwade** [comment]
@accesstechnology-mike we have this pretty much working now. You will need a Google Cloud TTS auth json file - or your Azure Creds to fill into the config.. It will be done in a couple of days.. So you can do that

Google cloud auth is harder.. Details here

Creating a service account for OAuth 2.0 involves generating credentials for a non-human user, often used in server-to-server interactions. Here's how you can create OAuth 2.0 credentials using a service account for Google APIs:

1. Go to the Google Cloud Console:
Visit the [Google Cloud Console](https://console.cloud.google.com/).



2. Create a New Project:
If you don't have a project already, create a new project in the developer console.



3. Enable APIs:
Enable the APIs that your service account will be using. For example, if you're using Google Drive API, enable that API for your project.



4. Create a Service Account:
- In the Google Cloud Console, navigate to "IAM & Admin" > "Service accounts."
- Click on "Create Service Account."
- Enter a name for the service account and an optional description.
- Choose the role for the service account. This determines the permissions it will have.
- Click "Continue" to proceed.

5. Create and Download Credentials:
- On the next screen, you can choose to grant the service account a role on your project. You can also skip this step and grant roles later.
- Click "Create Key" to create and download the JSON key file. This file contains the credentials for your service account.
- Keep this JSON file secure and do not expose it publicly.

6. Use the Service Account Credentials:
- In your code, load the credentials from the JSON key file. The credentials can be used to authenticate and access the APIs on behalf of the service account.



7. Grant Required Permissions:
- If you skipped assigning roles during the service account creation, you can now grant roles to the service account by navigating to "IAM & Admin" > "IAM" and adding the service account's email address with the appropriate roles.

[Google Cloud Platform](https://console.cloud.google.com/)
Google Cloud Platform lets you build, deploy, and scale applications, websites, and services on the same infrastructure as Google.

**Comment by willwade** [comment]
This is pre-release but feel free to kick the tyres early: https://github.com/AceCentre/TranslateAndTTS/releases/tag/1.0
